# Generated by Django 3.1.3 on 2021-04-25 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20210419_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id_hashed',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(related_name='voters_set', through='user.Voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
