# Generated by Django 3.1.3 on 2021-04-25 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20210425_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(related_name='voters', through='user.Voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
